server.port: 8080

stat-server.url: http://localhost:9090

spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true

  sql.init.mode: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm-service
    username: main
    password: main

  logging.level.org.springframework:
          orm.jpa: INFO
          transaction: INFO
          interceptor: TRACE
          JpaTransactionManager: DEBUG