server.port: 8080

stat-server.url: http://stats-server:9090

spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true

  sql.init.mode: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ewm-service:5432/ewm-service
    username: user
    password: pass

  application.name: evm-service

  logging.level.org.springframework:
          orm.jpa: INFO
          transaction: INFO
          interceptor: TRACE
          JpaTransactionManager: DEBUG