server:
  port: 9090

spring:
  main.allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate.format_sql: true

  sql.init.mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://stats-server:5432/stats-server
    username: user
    password: pass